build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
codenotary:
  #https://github.com/codenotary/cas/issues/296
  #signer: patrick.broetto@gmail.com
  base_image: notary@home-assistant.io
args:
  EUFY_SECURITY_WS_VERSION: 1.7.1
